"""SQLite storage layer public facade."""

from __future__ import annotations

from .admin import (
    add_project_member,
    bind_session_to_project,
    create_cron_job,
    create_project,
    delete_cron_job,
    delete_project,
    get_due_cron_jobs,
    get_kv,
    get_project,
    get_session_project_id,
    get_user_project_role,
    list_cron_jobs,
    list_project_members,
    list_projects,
    remove_project_member,
    set_kv,
    unbind_session_from_project,
    update_cron_enabled,
    update_cron_last_run,
)
from .knowledge import (
    _normalize_entity_name,
    archive_low_confidence_facts,
    backfill_fact_entities,
    decay_facts,
    delete_facts,
    find_or_create_entity,
    get_all_entities,
    get_all_tags,
    get_behavior_facts,
    get_pending_learnings,
    get_safety_facts,
    list_knowledge,
    save_fact,
    save_fact_tags,
    save_facts_batch,
    save_learning,
    search_facts,
    search_facts_by_entity,
    search_facts_by_tags,
    search_facts_scored,
    update_fact_content,
    update_fact_usage,
    update_learning,
)
from .plans import (
    append_task_llm_call,
    create_plan,
    create_task,
    get_tasks_for_plan,
    update_plan_awaits_input,
    update_plan_goal,
    update_plan_install_proposal,
    update_plan_status,
    update_plan_usage,
    update_task,
    update_task_command,
    update_task_retry_count,
    update_task_review,
    update_task_substatus,
    update_task_usage,
)
from .sessions import (
    _fact_session_filter,
    _get_messages_filtered,
    count_messages,
    create_session,
    get_all_sessions,
    get_facts,
    get_oldest_messages,
    get_pending_items,
    get_plan_for_session,
    get_recent_messages,
    get_session,
    get_sessions_for_user,
    get_tasks_for_session,
    get_unprocessed_trusted_messages,
    get_untrusted_messages,
    mark_message_processed,
    mark_messages_processed,
    recover_stale_running,
    save_message,
    save_pending_item,
    session_has_install_proposal,
    session_owned_by,
    update_summary,
    upsert_session,
)
from .setup import init_db
from .shared import (
    SCHEMA,
    FactDict,
    MessageDict,
    PlanDict,
    SessionDict,
    TaskDict,
    _KEEP_LLM_CALLS,
    _json_text_or_none,
    _row_to_dict,
    _rows_to_dicts,
    _serialize_llm_calls,
    _serialize_task_args,
    _update_field,
    _update_fields,
    log,
)

__all__ = [
    name
    for name in globals()
    if not name.startswith("__") and not name.startswith("_")
]
